In [1]:
import numpy as np

### Array generation function

### Random generation function

### Array attributes

### Array methods

### Reshaping and resizing

1. Basic Array Creation

In [5]:
arr = np.array([1,2,3,4,5]) # it says same data type is compulsory
arr

array([1, 2, 3, 4, 5])

In [7]:
a = [1,2,3,4.1,5,"hello"]
np.array(a)  # everything will be converted to string here

array(['1', '2', '3', '4.1', '5', 'hello'], dtype='<U32')

2. Vectors and Metrics

In [12]:
# metrics are 2d and vectors are 2d
# [[1,2], [3,4]]

l = [[1,2], [3,4]]
l # 1d

[[1, 2], [3, 4]]

In [11]:
np.array(l) # 2d

array([[1, 2],
       [3, 4]])

3. Array generation function

In [14]:
np.arange(1,10,5) # similar to like python - we just added a-range

array([1, 6])

In [18]:
np.zeros(6) # -> vectors
np.zeros((6,6)) # -> metrics

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
np.linspace(1,5,10) # same space
# start, end, space interval

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

4. Random generation function

In [33]:
np.random.rand(15) # five randome elements in a array, value > 0

# normalization in numbers
# values bet 0 and 1

array([0.53109671, 0.06770307, 0.94176692, 0.99949565, 0.88977776,
       0.6455271 , 0.6767731 , 0.99091523, 0.71624572, 0.77232429,
       0.9071801 , 0.76333039, 0.40713027, 0.89881689, 0.33191193])

In [34]:
np.random.randn(15)

# standardization in numbers
# -3 to +3

array([-0.76306064, -0.57399008, -1.36633316, -1.94484686, -0.28477255,
       -0.94747579, -1.49564053,  0.35591445, -0.78067147,  0.20850938,
       -0.25179751, -0.59147476, -2.17607534, -1.31762161,  0.29971   ])

In [41]:
np.random.randint(10)

8

In [42]:
# random numbers bet 10 and 20
np.random.randint(10,20, 10)

array([17, 14, 16, 12, 10, 10, 10, 19, 15, 11])