In [2]:
import numpy as np

### Array generation function

### Random generation function

### Array attributes

### Array methods

### Reshaping and resizing

1. Basic Array Creation

In [3]:
arr = np.array([1,2,3,4,5]) # it says same data type is compulsory
arr

array([1, 2, 3, 4, 5])

In [4]:
a = [1,2,3,4.1,5,"hello"]
np.array(a)  # everything will be converted to string here

array(['1', '2', '3', '4.1', '5', 'hello'], dtype='<U32')

2. Vectors and Metrics

In [5]:
# metrics are 2d and vectors are 2d
# [[1,2], [3,4]]

l = [[1,2], [3,4]]
l # 1d

[[1, 2], [3, 4]]

In [6]:
np.array(l) # 2d

array([[1, 2],
       [3, 4]])

3. Array generation function

In [7]:
np.arange(1,10,5) # similar to like python - we just added a-range

array([1, 6])

In [8]:
np.zeros(6) # -> vectors
np.zeros((6,6)) # -> metrics

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [9]:
np.ones((6,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
np.linspace(1,5,10) # same space
# start, end, space interval

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

4. Random generation function

In [11]:
np.random.rand(15) # five randome elements in a array, value > 0

# normalization in numbers
# values bet 0 and 1

array([0.42328714, 0.19004398, 0.20663258, 0.55285654, 0.68159533,
       0.65028416, 0.83036581, 0.64427692, 0.88342776, 0.55757638,
       0.07042994, 0.63203979, 0.2210596 , 0.17593141, 0.12530112])

In [12]:
np.random.randn(15)

# standardization in numbers
# -3 to +3

array([ 0.30816711,  2.08402287, -0.46497014, -2.54144215,  1.27510807,
        1.40895094, -0.97877314, -1.03735738, -1.28060061,  0.37074623,
        1.87728432,  1.58861406,  0.23046184,  0.82645833, -0.94409684])

In [13]:
np.random.randint(10)

8

In [14]:
# random numbers bet 10 and 20
np.random.randint(10,20, 10)

array([18, 11, 17, 19, 19, 11, 15, 17, 12, 11])

5. Array attributes

In [19]:
arr = np.array([[1,3],[4,55],[6,7]])

In [20]:
arr.shape ## atribute | so no use of "." after shape

(3, 2)

In [21]:
arr.size

6

In [22]:
arr.dtype

dtype('int64')

6. Array methods

In [24]:
# finding min and max elements
arr

array([[ 1,  3],
       [ 4, 55],
       [ 6,  7]])

In [25]:
arr.min()

np.int64(1)

In [26]:
arr.max()

np.int64(55)

In [27]:
arr.sum()

np.int64(76)

In [30]:
# summation of rows and columns
np.sum(arr, axis = 0)

# provided arr and axis as per required for summation
# columnwise -> 0 | rowswise -> 1

array([11, 65])

In [31]:
 arr.mean()

np.float64(12.666666666666666)

In [32]:
arr.std() # standard deviation

np.float64(19.03213656482693)

In [34]:
# index of argument max and min
# index of max element
arr.argmax()

np.int64(3)

In [35]:
arr.argmin()

np.int64(0)

7. Resizing and reshaping

In [38]:
array = np.arange(1,31)
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [40]:
# reshape the array
array.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

### Array Indexing and slicing of vectors

### Array/Numpy indexing and slicing of matrix

### Boolean indexing

1. Array indexing and slicing of vectors

In [41]:
t = np.arange(11,21)
t

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [43]:
t[6] # indexing

np.int64(17)

In [45]:
t[1:6:1] # slciing

array([12, 13, 14, 15, 16])

In [ ]:
2. Array indexing and slicin